In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 25520.7734
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 360.8932
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 352.5689
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 342.9752
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 331.7527
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 318.7600
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 305.1052
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 289.3262
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 272.5771
Epoch 10/100
240/240 [==============================] - 1s 3ms/step - loss: 255.5061
Epoch 11/100
240/240 [==============================] - 1s 2ms/step - loss: 237.4938
Epoch 12/100
240/240 [==============================] - 1s 2ms/step - lo

In [ ]:
y_pred = ann.predict(X_test)

60/60 [==============================] - 0s 1ms/step


In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)), 1))

[[432.71 431.23]
 [463.79 460.01]
 [467.3  461.14]
 ...
 [474.54 473.26]
 [441.23 438.  ]
 [460.49 463.28]]
